// AUTO-GENERATED by scripts/generate-locales.mjs — DO NOT EDIT MANUALLY
// Generated at: 2026-02-26T03:52:41.232Z
// Source: app.languages table (is_active = true)
export const locales = ['es', 'en', 'fr'] as const;
export const defaultLocale = 'es' as const;
export type Locale = (typeof locales)[number];
