// AUTO-GENERATED by scripts/generate-locales.mjs — DO NOT EDIT MANUALLY
// Generated at: 2026-02-15T22:04:10.733Z
// Source: app.languages table (is_active = true)
export const locales = ['es', 'en'] as const;
export const defaultLocale = 'es' as const;
export type Locale = (typeof locales)[number];
