// AUTO-GENERATED by scripts/generate-locales.mjs — DO NOT EDIT MANUALLY
// Generated at: 2026-02-14T00:00:00.000Z
// Source: app.languages table (is_active = true)
export const locales = ['es', 'en', 'fr', 'it'] as const;
export const defaultLocale = 'es' as const;
export type Locale = (typeof locales)[number];
