/**
 * scripts/generate-locales.mjs
 * Prebuild script: queries app.languages from Supabase and writes generated-locales.ts
 * Run with: node scripts/generate-locales.mjs
 */

import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';
import { writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = resolve(__dirname, '../src/infrastructure/config/generated-locales.ts');

// Cargar .env.local si existe
const envPath = resolve(__dirname, '../.env.local');
if (existsSync(envPath)) {
  config({ path: envPath });
}

const FALLBACK_LOCALES = ['es', 'en'];
const FALLBACK_DEFAULT = 'es';

async function main() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;

  if (!url || !key) {
    console.warn('[generate-locales] No Supabase env vars found. Using fallback locales.');
    writeFile(FALLBACK_LOCALES, FALLBACK_DEFAULT);
    return;
  }

  try {
    const supabase = createClient(url, key);
    const { data, error } = await supabase
      .schema('app')
      .from('languages')
      .select('code, is_default')
      .eq('is_active', true)
      .order('order_index')
      .order('code');

    if (error) throw error;

    if (!data || data.length === 0) {
      console.warn('[generate-locales] No active languages found in DB. Using fallback.');
      writeFile(FALLBACK_LOCALES, FALLBACK_DEFAULT);
      return;
    }

    const codes = data.map((l) => l.code);
    const defaultLang = data.find((l) => l.is_default)?.code || codes[0];

    console.log(`[generate-locales] Found ${codes.length} active languages: ${codes.join(', ')} (default: ${defaultLang})`);
    writeFile(codes, defaultLang);
  } catch (err) {
    console.warn('[generate-locales] Failed to query DB:', err.message);
    console.warn('[generate-locales] Using fallback locales.');
    writeFile(FALLBACK_LOCALES, FALLBACK_DEFAULT);
  }
}

function writeFile(codes, defaultLocale) {
  const localesLiteral = codes.map((c) => `'${c}'`).join(', ');
  const content = `// AUTO-GENERATED by scripts/generate-locales.mjs — DO NOT EDIT MANUALLY
// Generated at: ${new Date().toISOString()}
// Source: app.languages table (is_active = true)
export const locales = [${localesLiteral}] as const;
export const defaultLocale = '${defaultLocale}' as const;
export type Locale = (typeof locales)[number];
`;
  writeFileSync(OUTPUT_PATH, content, 'utf-8');
  console.log(`[generate-locales] Wrote ${OUTPUT_PATH}`);
}

main();
